# Streamlit Cloud secrets.toml file

# Backend API URL - change this to your Vercel deployment URL when deployed
BACKEND_API_URL = "https://your-vercel-app-url.vercel.app/api"

# Any other secrets needed for your app
# MISTRAL_API_KEY = "your-api-key-here"  # Only uncomment if you want to use the API directly from Streamlit 